"""套用 family-potential AI 全字審查結果"""
import json, os, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
VOCAB = os.path.normpath(os.path.join(HERE, '..', '..', '..', '..', 'vocab.json'))
with open(VOCAB,'r',encoding='utf-8') as f: data=json.load(f)
words = data['words']
idx = {w['word']: w for w in words}

# 高信心衍生關係(base 必須存在於 vocab,note 白話 + 文法名詞)
ADDS = {
    # === 不規則動詞過去式/分詞 ===
    'snuck':       ('sneak', '已經偷溜過的版本(不規則過去式)'),
    'smelt':       ('smell', '已經聞過的版本(不規則過去式)'),
    'dwelt':       ('dwell', '已經居住過的版本(不規則過去式)'),
    'learnt':      ('learn', '已經學過的版本(不規則過去式,英式)'),
    'leapt':       ('leap',  '已經跳過的版本(不規則過去式)'),
    'fled':        ('flee',  '已經逃過的版本(不規則過去式)'),
    'flung':       ('fling', '已經扔過的版本(不規則過去式)'),
    'spun':        ('spin',  '已經旋轉過的版本(不規則過去式)'),

    # === -ed 形容詞(描述人/物的狀態) ===
    'stressed':    ('stress',  '人覺得有壓力的(描述人,+ed 形容詞)'),
    'depressed':   ('depress', '人覺得憂鬱的(描述人,+ed 形容詞)'),
    'ashamed':     ('shame',   '人覺得羞愧的(描述人,a + shame + d)'),
    'delighted':   ('delight', '人覺得開心的(描述人,+ed 形容詞)'),
    'thrilled':    ('thrill',  '人覺得興奮的(描述人,+ed 形容詞)'),
    'frustrated':  ('frustrate','人覺得挫敗的(描述人,+ed 形容詞)'),
    'motivated':   ('motivate','人覺得有動力的(+ed 形容詞)'),
    'determined':  ('determine','人很堅定的(+ed 形容詞)'),
    'introverted': ('introvert','個性內向的(+ed 形容詞)'),
    'extroverted': ('extrovert','個性外向的(+ed 形容詞)'),
    'committed':   ('commit',  '已經承諾的(過去式/+ed 形容詞,雙 t)'),
    'curved':      ('curve',   '彎曲的(+ed 形容詞)'),
    'bearded':     ('beard',   '有鬍子的(+ed 形容詞)'),
    'tanned':      ('tan',     '曬黑的(+ed 形容詞,雙 n)'),
    'sunburned':   ('sunburn', '曬傷的(+ed 形容詞)'),
    'braided':     ('braid',   '編成辮子的(+ed 形容詞)'),
    'tattooed':    ('tattoo',  '有刺青的(+ed 形容詞)'),
    'pierced':     ('pierce',  '穿洞過的(+ed 形容詞)'),
    'polished':    ('polish',  '擦亮過的(+ed 形容詞)'),
    'refined':     ('refine',  '精緻的(+ed 形容詞)'),
    'dimpled':     ('dimple',  '有酒窩的(+ed 形容詞)'),
    'aged':        ('age',     '年長的(+ed 形容詞)'),
    'biased':      ('bias',    '有偏見的(+ed 形容詞)'),

    # === -y 形容詞 ===
    'wrinkly':     ('wrinkle', '形容詞版本(去 e + y,皺巴巴的)'),
    'smiley':      ('smile',   '形容詞版本(去 e + y,愛笑的)'),
    'curvy':       ('curve',   '形容詞版本(去 e + y,曲線玲瓏的)'),
    'bloody':      ('blood',   '形容詞版本(+y,血腥的)'),
    'mighty':      ('might',   '形容詞版本(+y,強大的)'),
    'scary':       ('scare',   '形容詞版本(去 e + y,可怕的)'),
    'shady':       ('shade',   '形容詞版本(去 e + y,陰涼的/可疑的)'),
    'thrifty':     ('thrift',  '形容詞版本(+y,節儉的)'),
    'hungry':      ('hunger',  '形容詞版本(+y,飢餓的)'),

    # === -ish 形容詞 ===
    'foolish':     ('fool',    '形容詞版本(+ish,愚蠢的)'),
    'childish':    ('child',   '形容詞版本(+ish,孩子氣的)'),

    # === -en 動詞化 ===
    'awaken':      ('awake',   '動詞版本(+n,喚醒)'),
    'lessen':      ('less',    '動詞版本(+en,減少)'),
    'lengthen':    ('length',  '動詞版本(+en,加長)'),
    'sharpen':     ('sharp',   '動詞版本(+en,使尖銳)'),
    'soften':      ('soft',    '動詞版本(+en,使柔軟)'),
    'straighten':  ('straight','動詞版本(+en,弄直)'),
    'heighten':    ('height',  '動詞版本(+en,提高)'),
    'strengthen':  ('strength','動詞版本(+en,加強)'),
    'deafen':      ('deaf',    '動詞版本(+en,使聽不見)'),
    'deepen':      ('deep',    '動詞版本(+en,加深)'),
    'harden':      ('hard',    '動詞版本(+en,使變硬)'),
    'lighten':     ('light',   '動詞版本(+en,變輕/變亮)'),
    'loosen':      ('loose',   '動詞版本(+n,鬆開)'),
    'shorten':     ('short',   '動詞版本(+en,縮短)'),
    'threaten':    ('threat',  '動詞版本(+en,威脅)'),
    'tighten':     ('tight',   '動詞版本(+en,使更緊)'),
    'weaken':      ('weak',    '動詞版本(+en,削弱)'),
    'widen':       ('wide',    '動詞版本(+en,加寬)'),
    'frighten':    ('fright',  '動詞版本(+en,使害怕)'),

    # === -ity / -ty 名詞化 ===
    'humility':    ('humble',  '名詞版本(-ity 把形容詞變名詞,謙虛)'),
    'validity':    ('valid',   '名詞版本(+ity,有效性)'),
    'vitality':    ('vital',   '名詞版本(+ity,活力)'),
    'formality':   ('formal',  '名詞版本(+ity,形式)'),
    'locality':    ('local',   '名詞版本(+ity,地區)'),
    'mortality':   ('mortal',  '名詞版本(+ity,死亡率)'),
    'nobility':    ('noble',   '名詞版本(+ity,貴族)'),
    'totality':    ('total',   '名詞版本(+ity,全部)'),
    'visibility':  ('visible', '名詞版本(+ity,能見度)'),
    'immunity':    ('immune',  '名詞版本(+ity,免疫力)'),
    'insanity':    ('insane',  '名詞版本(+ity,瘋狂)'),
    'legality':    ('legal',   '名詞版本(+ity,合法性)'),
    'mentality':   ('mental',  '名詞版本(+ity,心態)'),
    'eternity':    ('eternal', '名詞版本(+ity,永恆)'),
    'fertility':   ('fertile', '名詞版本(+ity,生育力)'),
    'hostility':   ('hostile', '名詞版本(+ity,敵意)'),
    'minority':    ('minor',   '名詞版本(+ity,少數)'),
    'maturity':    ('mature',  '名詞版本(+ity,成熟)'),
    'safety':      ('safe',    '名詞版本(+ty,安全)'),
    'honesty':     ('honest',  '名詞版本(+y,誠實)'),
    'difficulty':  ('difficult','名詞版本(+y,困難)'),
    'loyalty':     ('loyal',   '名詞版本(+ty,忠誠)'),
    'cruelty':     ('cruel',   '名詞版本(+ty,殘忍)'),
    'specialty':   ('special', '名詞版本(+ty,專長/招牌)'),
    'certainty':   ('certain', '名詞版本(+ty,確定性)'),
    'clarity':     ('clear',   '名詞版本(+ity,清晰)'),
    'complexity':  ('complex', '名詞版本(+ity,複雜度)'),
    'electricity': ('electric','名詞版本(+ity,電力)'),
    'purity':      ('pure',    '名詞版本(+ity,純度)'),
    'similarity':  ('similar', '名詞版本(+ity,相似)'),
    'nationality': ('nation',  '名詞版本(+ality,國籍)'),
    'personality': ('person',  '名詞版本(+ality,個性)'),
    'possibility': ('possible','名詞版本(+ity,可能性)'),
    'responsibility':('responsible','名詞版本(+ity,責任)'),
    'sustainability':('sustain','名詞版本(+ability,永續性)'),
    'virality':    ('viral',   '名詞版本(+ity,病毒式傳播)'),

    # === -tion/-sion 名詞化 ===
    'graduation':  ('graduate','這個動作的「事件」(+tion 名詞,畢業典禮)'),
    'eruption':    ('erupt',   '這個動作的「事件」(+tion 名詞,噴發)'),
    'adoption':    ('adopt',   '這個動作的「結果」(+tion 名詞,收養)'),
    'congestion':  ('congest', '這個動作的「結果」(+tion 名詞,壅塞)'),
    'comprehension':('comprehend','這個動作的「結果」(+sion 名詞,理解)'),
    'description': ('describe','這個動作的「結果」(+ption 名詞,描述)'),
    'destruction': ('destroy', '這個動作的「結果」(+tion 名詞,破壞)'),
    'discrimination':('discriminate','這個動作的「結果」(+ion 名詞,歧視)'),
    'distraction': ('distract','這個動作的「結果」(+ion 名詞,分心)'),
    'execution':   ('execute', '這個動作的「結果」(+ion 名詞,執行)'),
    'expression':  ('express', '這個動作的「結果」(+ion 名詞,表達)'),
    'evacuation':  ('evacuate','這個動作的「事件」(+tion 名詞,撤離)'),
    'abduction':   ('abduct',  '這個動作的「結果」(+ion 名詞,綁架)'),
    'investigation':('investigate','這個動作的「結果」(+ion 名詞,調查)'),
    'conviction':  ('convict', '這個動作的「結果」(+ion 名詞,定罪)'),
    'prosecution': ('prosecute','這個動作的「結果」(+ion 名詞,起訴)'),
    'interrogation':('interrogate','這個動作的「結果」(+ion 名詞,審問)'),
    'inspection':  ('inspect', '這個動作的「結果」(+ion 名詞,檢查)'),
    'instruction': ('instruct','這個動作的「結果」(+ion 名詞,指示)'),
    'invention':   ('invent',  '這個動作的「結果」(+ion 名詞,發明)'),
    'intention':   ('intend',  '這個動作的「結果」(+tion 名詞,意圖)'),
    'interruption':('interrupt','這個動作的「事件」(+ion 名詞,打斷)'),
    'innovation':  ('innovate','這個動作的「結果」(+ion 名詞,創新)'),
    'invasion':    ('invade',  '這個動作的「事件」(+sion 名詞,入侵)'),
    'objection':   ('object',  '這個動作的「結果」(+ion 名詞,反對)'),
    'oppression':  ('oppress', '這個動作的「結果」(+ion 名詞,壓迫)'),
    'permission':  ('permit',  '這個動作的「結果」(+ssion 名詞,許可)'),
    'pollution':   ('pollute', '這個動作的「結果」(+ion 名詞,汙染)'),
    'reflection':  ('reflect', '這個動作的「結果」(+ion 名詞,反射)'),
    'rejection':   ('reject',  '這個動作的「結果」(+ion 名詞,拒絕)'),
    'prediction':  ('predict', '這個動作的「結果」(+ion 名詞,預測)'),
    'prevention':  ('prevent', '這個動作的「結果」(+ion 名詞,預防)'),
    'projection':  ('project', '這個動作的「結果」(+ion 名詞,投影)'),
    'prohibition': ('prohibit','這個動作的「結果」(+ion 名詞,禁止)'),
    'restriction': ('restrict','這個動作的「結果」(+ion 名詞,限制)'),
    'revision':    ('revise',  '這個動作的「結果」(+ion 名詞,修訂)'),
    'profession':  ('profess', '這個動作的「結果」(+ion 名詞,職業)'),
    'possession':  ('possess', '這個動作的「結果」(+ion 名詞,擁有)'),
    'recognition': ('recognize','這個動作的「結果」(+tion 名詞,認可)'),
    'relation':    ('relate',  '這個動作的「結果」(+ion 名詞,關係)'),
    'reaction':    ('react',   '這個動作的「結果」(+ion 名詞,反應)'),
    'addiction':   ('addict',  '這個動作的「結果」(+ion 名詞,成癮)'),
    'selection':   ('select',  '這個動作的「結果」(+ion 名詞,選擇)'),
    'suggestion':  ('suggest', '這個動作的「結果」(+ion 名詞,建議)'),
    'emission':    ('emit',    '這個動作的「結果」(+ssion 名詞,排放)'),
    'mutation':    ('mutate',  '這個動作的「結果」(+ion 名詞,突變)'),
    'evolution':   ('evolve',  '這個動作的「結果」(+ution 名詞,演化)'),
    'occupation':  ('occupy',  '這個動作的「結果」(+ation 名詞,職業)'),
    'liberation':  ('liberate','這個動作的「事件」(+ion 名詞,解放)'),
    'communication':('communicate','這個動作的「結果」(+ion 名詞,溝通)'),
    'contamination':('contaminate','這個動作的「結果」(+ion 名詞,汙染)'),
    'colonization':('colonize','這個動作的「事件」(+ation 名詞,殖民)'),
    'explanation': ('explain', '這個動作的「結果」(+ation 名詞,解釋)'),
    'frustration': ('frustrate','這個動作的「結果」(+ion 名詞,挫敗)'),
    'imitation':   ('imitate', '這個動作的「結果」(+ion 名詞,模仿)'),
    'impression':  ('impress', '這個動作的「結果」(+ion 名詞,印象)'),
    'indignation': ('indignant','這個動作的「結果」(+ation 名詞,憤慨)'),
    'imitation':   ('imitate', '這個動作的「結果」(+ion 名詞,模仿)'),
    'destination': ('destine', '這個動作的「結果」(+ation 名詞,目的地)'),
    'discovery':   ('discover','這個動作的「結果」(+y 名詞,發現)'),
    'fascination': ('fascinate','這個動作的「結果」(+ion 名詞,著迷)'),
    'federation':  ('federate','這個動作的「結果」(+ation 名詞,聯邦)'),
    'compensation':('compensate','這個動作的「結果」(+ion 名詞,補償)'),
    'complication':('complicate','這個動作的「結果」(+ion 名詞,併發症)'),
    'precision':   ('precise', '這個動作的「品質」(+sion 名詞,精準)'),
    'qualification':('qualify','這個動作的「結果」(+cation 名詞,資格)'),
    'satisfaction':('satisfy', '這個動作的「結果」(+action 名詞,滿足)'),
    'restoration': ('restore', '這個動作的「結果」(+ation 名詞,復原)'),
    'simplification':('simplify','這個動作的「結果」(+cation 名詞,簡化)'),
    'notification':('notify',  '這個動作的「結果」(+cation 名詞,通知)'),
    'punctuation': ('punctuate','這個動作的「結果」(+tion 名詞,標點符號)'),
    'depreciation':('depreciate','這個動作的「結果」(+tion 名詞,折舊)'),
    'encryption':  ('encrypt', '這個動作的「結果」(+tion 名詞,加密)'),
    'unification': ('unify',   '這個動作的「結果」(+cation 名詞,統一)'),
    'litigation':  ('litigate','這個動作的「結果」(+tion 名詞,訴訟)'),
    'aviation':    ('aviate',  '這個動作的「結果」(+ation 名詞,航空)'),
    'migration':   ('migrate', '這個動作的「事件」(+ion 名詞,遷徙)'),
    'oppression':  ('oppress', '這個動作的「結果」(+ion 名詞,壓迫)'),
    'concession':  ('concede', '這個動作的「結果」(+sion 名詞,讓步)'),
    'conception':  ('conceive','這個動作的「結果」(+tion 名詞,觀念)'),
    'contradiction':('contradict','這個動作的「結果」(+ion 名詞,矛盾)'),
    'intersection':('intersect','這個動作的「事件」(+ion 名詞,十字路口)'),
    'irritation':  ('irritate','這個動作的「結果」(+ion 名詞,刺激)'),
    'assumption':  ('assume',  '這個動作的「結果」(+ption 名詞,假設)'),
    'reputation':  ('repute',  '這個動作的「結果」(+ation 名詞,名聲)'),
    'recommendation':('recommend','這個動作的「結果」(+ation 名詞,推薦)'),
    'stimulation': ('stimulate','這個動作的「結果」(+ion 名詞,刺激)'),
    'dedication':  ('dedicate','這個動作的「結果」(+ion 名詞,奉獻)'),
    'dictation':   ('dictate', '這個動作的「結果」(+ion 名詞,聽寫)'),
    'abolition':   ('abolish', '這個動作的「結果」(+ition 名詞,廢除)'),
    'abdication':  ('abdicate','這個動作的「事件」(+ion 名詞,退位)'),
    'excavation':  ('excavate','這個動作的「結果」(+ion 名詞,挖掘)'),
    'emigration':  ('emigrate','這個動作的「事件」(+ation 名詞,移出)'),
    'rebellion':   ('rebel',   '這個動作的「事件」(+lion 名詞,叛亂)'),
    'reunion':     ('reunite', '這個動作的「事件」(+ion 名詞,重聚)'),
    'devotion':    ('devote',  '這個動作的「結果」(+ion 名詞,奉獻)'),
    'diversion':   ('divert',  '這個動作的「結果」(+sion 名詞,轉移)'),
    'subscription':('subscribe','這個動作的「結果」(+ption 名詞,訂閱)'),
    'negotiation': ('negotiate','這個動作的「事件」(+ion 名詞,談判)'),
    'comparison':  ('compare', '這個動作的「結果」(+ison 名詞,比較)'),
    'collection':  ('collect', '這個動作的「結果」(+ion 名詞,收藏)'),
    'preservation':('preserve','這個動作的「結果」(+ation 名詞,保存)'),
    'participation':('participate','這個動作的「結果」(+ation 名詞,參與)'),
    'perfection':  ('perfect', '這個動作的「結果」(+ion 名詞,完美)'),
    'anticipation':('anticipate','這個動作的「結果」(+ion 名詞,期待)'),
    'abbreviation':('abbreviate','這個動作的「結果」(+ion 名詞,縮寫)'),
    'aggression':  ('aggress', '這個動作的「結果」(+ion 名詞,侵略)'),
    'annoyance':   ('annoy',   '這個動作的「結果」(+ance 名詞,厭煩)'),

    # === 名詞 ↔ 形容詞 對應 ===
    'difference':  ('different','名詞版本(+ence,差別)'),
    'importance':  ('important','名詞版本(+ance,重要性)'),
    'patience':    ('patient', '名詞版本(+ence,耐心)'),
    'pleasure':    ('please',  '名詞版本(+ure,愉悅)'),
    'presence':    ('present', '名詞版本(+ence,在場)'),
    'absence':     ('absent',  '名詞版本(+ence,缺席)'),
    'excellence':  ('excellent','名詞版本(+ence,優秀)'),
    'response':    ('respond', '名詞版本(+se,回應)'),
    'success':     ('succeed', '名詞版本(succeed→success,成功)'),
    'reliance':    ('rely',    '名詞版本(+ance,依賴)'),
    'persistence': ('persist', '名詞版本(+ence,堅持)'),
    'tendency':    ('tend',    '名詞版本(+ency,傾向)'),
    'tolerance':   ('tolerate','名詞版本(+ance,容忍)'),
    'governance':  ('govern',  '名詞版本(+ance,治理)'),
    'compliance':  ('comply',  '名詞版本(+ance,遵從)'),
    'observance':  ('observe', '名詞版本(+ance,遵守)'),
    'resemblance': ('resemble','名詞版本(+ance,相像)'),
    'resistance':  ('resist',  '名詞版本(+ance,抵抗)'),
    'reference':   ('refer',   '名詞版本(+ence,參考)'),
    'preference':  ('prefer',  '名詞版本(+ence,偏好)'),
    'insistence':  ('insist',  '名詞版本(+ence,堅持)'),
    'disturbance': ('disturb', '名詞版本(+ance,打擾)'),
    'failure':     ('fail',    '名詞版本(+ure,失敗)'),
    'exposure':    ('expose',  '名詞版本(+ure,曝光)'),
    'closure':     ('close',   '名詞版本(+ure,結束)'),
    'enclosure':   ('enclose', '名詞版本(+ure,圍場)'),
    'disclosure':  ('disclose','名詞版本(+ure,揭露)'),
    'pregnancy':   ('pregnant','名詞版本(+cy,懷孕)'),
    'literacy':    ('literate','名詞版本(+cy,識字)'),
    'presidency':  ('president','名詞版本(+cy,總統職位)'),
    'bankruptcy':  ('bankrupt','名詞版本(+cy,破產)'),
    'agency':      ('agent',   '名詞版本(+cy,機構)'),
    'emergency':   ('emerge',  '名詞版本(+ency,緊急)'),
    'descent':     ('descend', '名詞版本(descend→descent,下降)'),
    'applause':    ('applaud', '名詞版本(applaud→applause,鼓掌)'),

    # === -er/-or 職業 ===
    'prosecutor':  ('prosecute','做這件事的人(+or,檢察官)'),
    'senator':     ('senate',  '在這裡工作的人(+or,參議員)'),
    'correspondent':('correspond','做這件事的人(+ent,通訊記者)'),
    'columnist':   ('column',  '做這件事的人(+ist,專欄作家)'),
    'vlogger':     ('vlog',    '做這件事的人(+ger 雙 g,Vlog 主)'),
    'missionary':  ('mission', '做這件事的人(+ary,傳教士)'),
    'therapist':   ('therapy', '做這件事的人(+ist,治療師)'),
    'counselor':   ('counsel', '做這件事的人(+or,諮商師)'),
    'analyst':     ('analyze', '做這件事的人(+yst,分析師)'),
    'biologist':   ('biology', '做這件事的人(+ist,生物學家)'),
    'chemist':     ('chemistry','做這件事的人(+ist,化學家)'),
    'physicist':   ('physics', '做這件事的人(+ist,物理學家)'),
    'economist':   ('economy', '做這件事的人(+ist,經濟學家)'),
    'psychologist':('psychology','做這件事的人(+ist,心理學家)'),
    'sociologist': ('sociology','做這件事的人(+ist,社會學家)'),
    'historian':   ('history', '做這件事的人(+ian,歷史學家)'),
    'philosopher': ('philosophy','做這件事的人(+er,哲學家)'),
    'novelist':    ('novel',   '做這件事的人(+ist,小說家)'),
    'astronomer':  ('astronomy','做這件事的人(+er,天文學家)'),
    'pianist':     ('piano',   '做這件事的人(+ist,鋼琴家)'),
    'violinist':   ('violin',  '做這件事的人(+ist,小提琴家)'),
    'specialist':  ('special', '做這件事的人(+ist,專家)'),
    'killer':      ('kill',    '做這件事的人(+er,殺手)'),
    'fighter':     ('fight',   '做這件事的人(+er,戰士)'),
    'runner':      ('run',     '做這件事的人(+ner 雙 n,跑者)'),
    'astronaut':   ('astronaut',None),  # skip
    'illustrator': ('illustrate','做這件事的人(+or,插畫家)'),
    'animator':    ('animate', '做這件事的人(+or,動畫師)'),
    'investor':    ('invest',  '做這件事的人(+or,投資人)'),
    'inventor':    ('invent',  '做這件事的人(+or,發明家)'),
    'contractor':  ('contract','做這件事的人(+or,承包商)'),
    'consultant':  ('consult', '做這件事的人(+ant,顧問)'),
    'attendant':   ('attend',  '做這件事的人(+ant,服務員)'),
    'inhabitant':  ('inhabit', '住在這裡的人(+ant,居民)'),
    'emigrant':    ('emigrate','做這件事的人(+ant,移出者)'),
    'immigrant':   ('immigrate','做這件事的人(+ant,移入者)'),
    'combatant':   ('combat',  '做這件事的人(+ant,戰鬥員)'),
    'opponent':    ('oppose',  '做這件事的人(+ent,對手)'),
    'resident':    ('reside',  '住在這裡的人(+ent,居民)'),
    'lobbyist':    ('lobby',   '做這件事的人(+ist,遊說者)'),
    'activist':    ('active',  '做這件事的人(+ist,行動者)'),
    'strategist':  ('strategy','做這件事的人(+ist,策略家)'),
    'tourist':     ('tour',    '做這件事的人(+ist,遊客)'),
    'pharmacist':  ('pharmacy','做這件事的人(+ist,藥劑師)'),
    'dictator':    ('dictate', '做這件事的人(+or,獨裁者)'),
    'administrator':('administrate','做這件事的人(+or,管理員)'),
    'editor':      ('edit',    '做這件事的人(+or,編輯)'),
    'crusader':    ('crusade', '做這件事的人(+r,十字軍)'),
    'sniper':      ('snipe',   '做這件事的人(+r,狙擊手)'),
    'twister':     ('twist',   '做這件事的東西(+er,龍捲風)'),
    'freelancer':  ('freelance','做這件事的人(+r,自由工作者)'),
    'bartender':   ('bartend', '做這件事的人(+er,酒保)'),
    'newscaster':  ('newscast','做這件事的人(+er,新聞主播)'),
    'propeller':   ('propel',  '做這件事的東西(+ler 雙 l,推進器)'),
    'sanitizer':   ('sanitize','做這件事的東西(+r,消毒液)'),
    'moisturizer': ('moisturize','做這件事的東西(+r,保濕乳)'),
    'tweezer':     ('tweeze',  '做這件事的東西(+r,鑷子)'),
    'appetizer':   ('appetite','做這件事的東西(+izer,開胃菜)'),
    'astronaut':   ('astronaut',None),  # skip
    'examinee':    ('examine', '被這件事影響的人(+ee,應試者)'),
    'sculptor':    ('sculpt',  '做這件事的人(+or,雕刻家)'),
    'hostess':     ('host',    '女主人(host + ess 陰性)'),
    'stewardess':  ('steward', '女服務員(steward + ess 陰性)'),
    'goddess':     ('god',     '女神(god + dess 陰性,雙 d)'),

    # === -less 形容詞 ===
    'ruthless':    ('ruth',    '「沒…的」(+less 形容詞,無情的;ruth 是古字「憐憫」)'),
    'seamless':    ('seam',    '「沒…的」(+less 形容詞,無縫的)'),

    # === -ly 副詞 ===
    'basically':   ('basic',   '副詞版本(+ally,基本上)'),
    'possibly':    ('possible','副詞版本(+ly,可能)'),
    'primarily':   ('primary', '副詞版本(+ily,主要)'),
    'initially':   ('initial', '副詞版本(+ly,起初)'),
    'instantly':   ('instant', '副詞版本(+ly,立刻)'),
    'proudly':     ('proud',   '副詞版本(+ly,驕傲地)'),
    'largely':     ('large',   '副詞版本(+ly,大部分)'),
    'previously':  ('previous','副詞版本(+ly,先前)'),
    'wholly':      ('whole',   '副詞版本(+ly,完全)'),
    'partially':   ('partial', '副詞版本(+ly,部分)'),
    'essentially': ('essential','副詞版本(+ly,本質上)'),
    'surprisingly':('surprising','副詞版本(+ly,意外地)'),
    'constantly':  ('constant','副詞版本(+ly,經常)'),
    'incredibly':  ('incredible','副詞版本(+ly,難以置信)'),
    'necessarily': ('necessary','副詞版本(+ily,必然)'),
    'regularly':   ('regular', '副詞版本(+ly,規律地)'),
    'rightly':     ('right',   '副詞版本(+ly,正確地)'),
    'successfully':('successful','副詞版本(+ly,成功地)'),
    'willingly':   ('willing', '副詞版本(+ly,願意地)'),
    'cowardly':    ('coward',  '副詞版本(+ly,膽小地)'),
    'deadly':      ('dead',    '形容詞版本(+ly,致命的;這個 -ly 是形容詞)'),
    'lively':      ('live',    '形容詞版本(+ly,有活力的;這個 -ly 是形容詞)'),
    'lovely':      ('love',    '形容詞版本(+ly,可愛的;這個 -ly 是形容詞)'),

    # === -ful / -ous 形容詞(漏掉的) ===
    'passionate':  ('passion', '充滿…的(+ate 形容詞,熱情的)'),
    'fortunate':   ('fortune', '形容詞版本(+ate,幸運的)'),
    'envious':     ('envy',    '充滿…的(+ous 形容詞,嫉妒的)'),
    'glorious':    ('glory',   '充滿…的(+ous 形容詞,光榮的)'),
    'gracious':    ('grace',   '充滿…的(+ious 形容詞,優雅的)'),
    'luxurious':   ('luxury',  '充滿…的(+ous 形容詞,奢華的)'),
    'mysterious':  ('mystery', '充滿…的(+ous 形容詞,神秘的)'),
    'miraculous':  ('miracle', '形容詞版本(+ous,奇蹟的)'),
    'ambitious':   ('ambition','充滿…的(+ous 形容詞,有野心的)'),
    'cautious':    ('caution', '形容詞版本(+ous,謹慎的)'),
    'disastrous':  ('disaster','形容詞版本(+ous,災難的)'),
    'superstitious':('superstition','形容詞版本(+ous,迷信的)'),
    'religious':   ('religion','形容詞版本(+ous,虔誠的)'),
    'horrible':    ('horror',  '形容詞版本(horror→horrible,可怕的)'),
    'horrify':     ('horror',  '動詞版本(+ify,使害怕)'),

    # === -ic/-ical 形容詞 ===
    'alcoholic':   ('alcohol', '形容詞版本(+ic,酒精的)'),
    'heroic':      ('hero',    '形容詞版本(+ic,英雄的)'),
    'magnetic':    ('magnet',  '形容詞版本(+ic,磁性的)'),
    'majestic':    ('majesty', '形容詞版本(+ic,雄偉的)'),
    'symbolic':    ('symbol',  '形容詞版本(+ic,象徵的)'),
    'sarcastic':   ('sarcasm', '形容詞版本(sarcasm→sarcastic,諷刺的)'),
    'philosophical':('philosophy','形容詞版本(+ical,哲學的)'),
    'analytical':  ('analyze', '形容詞版本(+ical,分析的)'),
    'grammatical': ('grammar', '形容詞版本(+ical,文法的)'),
    'clinical':    ('clinic',  '形容詞版本(+al,臨床的)'),
    'official':    ('office',  '形容詞版本(+ial,官方的)'),
    'spectacular': ('spectacle','形容詞版本(+ar,壯觀的)'),
    'mathematical':('mathematics','形容詞版本(+al,數學的)'),
    'biological':  ('biology', '形容詞版本(+ical,生物的)'),
    'romantic':    ('romance', '形容詞版本(romance→romantic,浪漫的)'),

    # === -tive 形容詞 ===
    'comparative': ('compare', '形容詞版本(+ative,比較的)'),
    'decisive':    ('decide',  '形容詞版本(+sive,決定性的)'),
    'effective':   ('effect',  '形容詞版本(+ive,有效的)'),
    'informative': ('inform',  '形容詞版本(+ative,資訊豐富的)'),
    'representative':('represent','形容詞/名詞(+ative,代表的)'),
    'talkative':   ('talk',    '形容詞版本(+ative,愛說話的)'),
    'expressive':  ('express', '形容詞版本(+ive,表達豐富的)'),
    'protective':  ('protect', '形容詞版本(+ive,保護的)'),

    # === -ent/-ant 形容詞 ===
    'dependent':   ('depend',  '形容詞版本(+ent,依賴的)'),
    'persistent':  ('persist', '形容詞版本(+ent,持續的)'),
    'pleasant':    ('please',  '形容詞版本(please→pleasant,愉快的)'),
    'tolerant':    ('tolerate','形容詞版本(+ant,容忍的)'),
    'triumphant':  ('triumph', '形容詞版本(+ant,得意的)'),
    'competent':   ('compete', '形容詞版本(+ent,稱職的)'),

    # === 否定前綴 ===
    'illegal':     ('legal',   '否定版本(il- + legal,非法的)'),
    'unlawful':    ('lawful',  '否定版本(un- + lawful,不合法的)'),
    'immoral':     ('moral',   '否定版本(im- + moral,不道德的)'),
    'injustice':   ('justice', '否定版本(in- + justice,不公正)'),
    'irrational':  ('rational','否定版本(ir- + rational,不理性的)'),
    'unconscious': ('conscious','否定版本(un- + conscious,無意識的)'),
    'dishonest':   ('honest',  '否定版本(dis- + honest,不誠實的)'),
    'impatient':   ('patient', '否定版本(im- + patient,沒耐心的)'),
    'immature':    ('mature',  '否定版本(im- + mature,不成熟的)'),
    'disappear':   ('appear',  '否定版本(dis- + appear,消失)'),
    'disadvantage':('advantage','否定版本(dis- + advantage,劣勢)'),
    'discomfort':  ('comfort', '否定版本(dis- + comfort,不舒服)'),
    'discover':    ('cover',   '前綴 dis- (dis + cover,發現)'),
    'disconnect':  ('connect', '否定版本(dis- + connect,斷開)'),
    'discourage':  ('courage', '否定版本(dis- + courage,使氣餒)'),
    'disapprove':  ('approve', '否定版本(dis- + approve,不贊同)'),
    'distrust':    ('trust',   '否定版本(dis- + trust,不信任)'),
    'undermine':   ('mine',    '前綴 under-(under + mine,破壞)'),
    'underestimate':('estimate','前綴 under-(低估)'),
    'uncover':     ('cover',   '否定版本(un- + cover,揭開)'),
    'disable':     ('able',    '否定版本(dis- + able,使失能)'),
    'mislead':     ('lead',    '前綴 mis-(誤導)'),
    'misunderstand':('understand','前綴 mis-(誤解)'),
    'misfortune':  ('fortune', '前綴 mis-(不幸)'),

    # === 複合詞 / 多動詞前綴 ===
    'overcome':    ('come',    '前綴 over-(克服)'),
    'overlook':    ('look',    '前綴 over-(忽略)'),

    # === 複數 / 拼字變化 ===
    'parents':     ('parent',  '「很多個」的版本(複數,+s)'),
    'groceries':   ('grocery', '「很多個」的版本(複數,y 變 ies)'),
    'glasses':     ('glass',   '「很多個」的版本(複數,+es)'),
    'crutches':    ('crutch',  '「很多個」的版本(複數,+es)'),
    'feelings':    ('feel',    '名詞版本(+ings,感受;複數常用)'),

    # === -ify 動詞化 ===
    'beautify':    ('beauty',  '動詞版本(+ify,美化)'),
    'notify':      ('notice',  '動詞版本(+ify,通知)'),
    'qualify':     ('quality', '動詞版本(+ify,使有資格)'),
    'simplify':    ('simple',  '動詞版本(+ify,簡化)'),
    'glorify':     ('glory',   '動詞版本(+ify,讚美)'),
    'amplify':     ('ample',   '動詞版本(+ify,擴大)'),
    'intensify':   ('intense', '動詞版本(+ify,加強)'),
    'purify':      ('pure',    '動詞版本(+ify,淨化)'),
    'diversify':   ('diverse', '動詞版本(+ify,多元化)'),

    # === -ize 動詞化 ===
    'memorize':    ('memory',  '動詞版本(+ize,記住)'),
    'summarize':   ('summary', '動詞版本(+ize,總結)'),
    'sympathize':  ('sympathy','動詞版本(+ize,同情)'),
    'stabilize':   ('stable',  '動詞版本(+ize,穩定)'),
    'jeopardize':  ('jeopardy','動詞版本(+ize,危及)'),
    'scrutinize':  ('scrutiny','動詞版本(+ize,仔細審查)'),
    'synthesize':  ('synthesis','動詞版本(+ize,合成)'),
    'plagiarize':  ('plagiary','動詞版本(+ize,剽竊)'),
    'originate':   ('origin',  '動詞版本(+ate,起源)'),
    'alienate':    ('alien',   '動詞版本(+ate,使疏遠)'),
    'assassinate': ('assassin','動詞版本(+ate,暗殺)'),

    # === 動詞前綴 re- / fore- ===
    'reproduce':   ('produce', '前綴 re-(再 + produce,繁殖)'),
    'foresee':     ('see',     '前綴 fore-(預見)'),

    # === 不規則複數 / 同源 ===
    'manners':     ('manner',  '「很多個」的版本(複數,禮貌)'),
    'savings':     ('save',    '名詞版本(+ings,儲蓄)'),
    'earnings':    ('earn',    '名詞版本(+ings,收入)'),
    'cosmetics':   ('cosmetic','「很多個」的版本(+s 名詞,化妝品)'),
    'electronics': ('electronic','「很多個」的版本(+s 名詞,電子產品)'),

    # === -ling 幼體 ===
    'duckling':    ('duck',    '幼體名詞(+ling,小鴨)'),

    # === 暱稱 ===
    'daddy':       ('dad',     '暱稱版本(+dy,爸爸;雙 d)'),
    'mommy':       ('mom',     '暱稱版本(+my,媽媽;雙 m)'),
    'kitty':       ('cat',     '暱稱版本(小貓的暱稱)'),

    # === 方位/位置複合 ===
    'upstairs':    ('stair',   '方位副詞(up + stairs,在樓上)'),
    'downstairs':  ('stair',   '方位副詞(down + stairs,在樓下)'),

    # === 性別變體 ===
    'firewoman':   ('fireman', '性別變體(man → woman,女消防員)'),

    # === 同源拼字變化(進階)===
    'diagnosis':   ('diagnose','名詞版本(動轉名,診斷)'),
    'dosage':      ('dose',    '名詞版本(+age,劑量)'),
    'allergic':    ('allergy', '形容詞版本(allergy→allergic,過敏的)'),
    'illness':     ('ill',     '名詞版本(+ness,生病)'),
    'contagious':  ('contagion','形容詞版本(contagion→contagious,傳染的)'),
    'anxious':     ('anxiety', '形容詞版本(與 anxiety 同根,焦慮的)'),
    'shortage':    ('short',   '名詞版本(+age,短缺)'),
    'passage':     ('pass',    '名詞版本(+age,通道)'),
    'jewelry':     ('jewel',   '名詞版本(+ry,珠寶)'),
    'machinery':   ('machine', '名詞版本(+ry,機械)'),
    'slavery':     ('slave',   '名詞版本(+ry,奴隸制)'),
    'scenery':     ('scene',   '名詞版本(+ry,風景)'),
    'rivalry':     ('rival',   '名詞版本(+ry,競爭)'),
    'singular':    ('single',  '形容詞版本(同根 sing-,單數的)'),
    'simplicity':  ('simple',  '名詞版本(+icity,簡單)'),
    'leadership':  ('leader',  '名詞版本(+ship,領導力)'),
    'ownership':   ('owner',   '名詞版本(+ship,所有權)'),
    'tourism':     ('tour',    '名詞版本(+ism,觀光業)'),
    'realism':     ('real',    '名詞版本(+ism,寫實主義)'),
    'sustainability':('sustain','名詞版本(+ability,永續性)'),

    # === 對應字 ===
    'absent':      ('absence', '形容詞版本(absent ↔ absence)'),
    'inquiry':     ('inquire', '名詞版本(+y,詢問)'),
    'descent':     ('descend', '名詞版本(descend→descent,血統/下降)'),

    # === -ant 形容詞名詞同根 ===
    'adolescent':  ('adolescence','形容詞/名詞(青少年的)'),

    # === 動詞名詞同源 ===
    'guilt':       ('guilty',  '名詞版本(guilty ↔ guilt,罪惡)'),
    'success':     ('succeed', '名詞版本(succeed→success,成功)'),
    'depress':     ('press',   '前綴 de-(壓抑)'),

    # === 還沒分類但 high-confidence ===
    'romance':     ('romance', None),  # skip - 本字
    'romantic':    ('romance', '形容詞版本(romance→romantic,浪漫的)'),
}

# 篩選只保留 base 真實存在的
n_add = 0
n_skip_no_base = 0
n_skip_dup = 0
for word, val in ADDS.items():
    if val is None or val[1] is None:
        continue
    base, note = val
    if word not in idx:
        continue
    if 'base' in idx[word]:
        n_skip_dup += 1
        continue
    if base not in idx:
        n_skip_no_base += 1
        continue
    idx[word]['base'] = base
    idx[word]['family-note'] = note
    n_add += 1

with open(VOCAB,'w',encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"新增家族線:       {n_add}")
print(f"略過(已有 base):   {n_skip_dup}")
print(f"略過(base 不存在): {n_skip_no_base}")
print(f"總 base:           {sum(1 for w in words if 'base' in w)}")
