"""套用 homophone-potential AI 全字審查結果"""
import json, os, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
VOCAB = os.path.normpath(os.path.join(HERE, '..', '..', '..', '..', 'vocab.json'))
with open(VOCAB,'r',encoding='utf-8') as f: data=json.load(f)
words = data['words']
idx = {w['word']: w for w in words}

# 高信心同音/易混提示(只挑常見高頻陷阱)
HOMO = {
    # === 真同音字 ===
    'four':       '⚠️ 同音字:four 四 / for 為了(ㄈㄛ)',
    'for':        '⚠️ 同音字:for 為了 / four 四(ㄈㄛ)',
    'by':         '⚠️ 同音字:by 經由 / buy 買 / bye 再見(ㄅㄞ)',
    'buy':        '⚠️ 同音字:buy 買 / by 經由 / bye 再見(ㄅㄞ)',
    'nose':       '⚠️ 同音字:nose 鼻子 / knows 知道(三單)',
    'sole':       '⚠️ 同音字:sole 唯一/鞋底 / soul 靈魂',
    'soul':       '⚠️ 同音字:soul 靈魂 / sole 唯一/鞋底',
    'waste':      '⚠️ 同音字:waste 浪費 / waist 腰部',
    'waist':      '⚠️ 同音字:waist 腰部 / waste 浪費',
    'piece':      '⚠️ 同音字:piece 一片 / peace 和平(peace of mind ≠ piece of mind)',
    'peace':      '⚠️ 同音字:peace 和平 / piece 一片',
    'fair':       '⚠️ 同音字:fair 公平/白皙 / fare 車費',
    'fare':       '⚠️ 同音字:fare 車費 / fair 公平/白皙',
    'hire':       '⚠️ 同音字:hire 僱用 / higher 更高',
    'higher':     '⚠️ 同音字:higher 更高 / hire 僱用',
    'site':       '⚠️ 同音字:site 地點 / cite 引用 / sight 視覺',
    'cite':       '⚠️ 同音字:cite 引用 / site 地點 / sight 視覺',
    'sight':      '⚠️ 同音字:sight 視覺 / site 地點 / cite 引用',
    'aid':        '⚠️ 同音字:aid 幫助 / aide 助理',
    'aide':       '⚠️ 同音字:aide 助理 / aid 幫助',
    'vise':       '⚠️ 同音字:vise 老虎鉗 / vice 惡習',
    'vice':       '⚠️ 同音字:vice 惡習 / vise 老虎鉗',
    'holy':       '⚠️ 近音字:holy 神聖的 / wholly 完全地',
    'wholly':     '⚠️ 近音字:wholly 完全地 / holy 神聖的',
    'prophet':    '⚠️ 同音字:prophet 先知 / profit 利潤',
    'alter':      '⚠️ 同音字:alter 改變 / altar 祭壇',
    'altar':      '⚠️ 同音字:altar 祭壇 / alter 改變',
    'poll':       '⚠️ 同音字:poll 民調 / pole 柱子/極',
    'pole':       '⚠️ 同音字:pole 柱子/極 / poll 民調',
    'summary':    '⚠️ 同音字:summary 摘要 / summery 夏天般的',
    'sundae':     '⚠️ 同音字:sundae 聖代 / Sunday 星期日',
    'mussel':     '⚠️ 同音字:mussel 貽貝 / muscle 肌肉',
    'navel':      '⚠️ 同音字:navel 肚臍 / naval 海軍的',
    'naval':      '⚠️ 同音字:naval 海軍的 / navel 肚臍',
    'bury':       '⚠️ 同音字:bury 埋 / berry 漿果',
    'berry':      '⚠️ 同音字:berry 漿果 / bury 埋',
    'due':        '⚠️ 同音字:due 到期的 / dew 露水 / do 做',
    'dew':        '⚠️ 同音字:dew 露水 / due 到期的',
    'oral':       '⚠️ 同音字:oral 口頭的 / aural 聽覺的',
    'aural':      '⚠️ 同音字:aural 聽覺的 / oral 口頭的',
    'coarse':     '⚠️ 同音字:coarse 粗糙的 / course 課程',
    'course':     '⚠️ 同音字:course 課程 / coarse 粗糙的',
    'flea':       '⚠️ 同音字:flea 跳蚤 / flee 逃離',
    'flee':       '⚠️ 同音字:flee 逃離 / flea 跳蚤',
    'pail':       '⚠️ 同音字:pail 桶子 / pale 蒼白的',
    'pale':       '⚠️ 同音字:pale 蒼白的 / pail 桶子',
    'main':       '⚠️ 同音字:main 主要的 / mane 馬鬃',
    'mane':       '⚠️ 同音字:mane 馬鬃 / main 主要的',
    'weigh':      '⚠️ 同音字:weigh 秤重 / way 方法',
    'hay':        '⚠️ 同音字:hay 乾草 / hey 嘿',
    'herd':       '⚠️ 同音字:herd 一群 / heard 聽見(過去式)',
    'heard':      '⚠️ 同音字:heard 聽見(過去式)/ herd 一群',
    'peer':       '⚠️ 同音字:peer 同儕 / pier 碼頭',
    'pier':       '⚠️ 同音字:pier 碼頭 / peer 同儕',
    'maze':       '⚠️ 同音字:maze 迷宮 / maize 玉米',
    'maize':      '⚠️ 同音字:maize 玉米 / maze 迷宮',
    'leak':       '⚠️ 同音字:leak 漏 / leek 韭蔥',
    'leek':       '⚠️ 同音字:leek 韭蔥 / leak 漏',
    'gait':       '⚠️ 同音字:gait 步態 / gate 大門',
    'foul':       '⚠️ 同音字:foul 惡臭的/犯規 / fowl 家禽',
    'fowl':       '⚠️ 同音字:fowl 家禽 / foul 惡臭的/犯規',
    'birth':      '⚠️ 同音字:birth 出生 / berth 臥鋪',
    'guilt':      '⚠️ 同音字:guilt 罪惡感 / gilt 鍍金的',
    'isle':       '⚠️ 同音字:isle 小島 / aisle 走道 / I\'ll',
    'aisle':      '⚠️ 同音字:aisle 走道 / isle 小島 / I\'ll',
    'foe':        '⚠️ 同音字:foe 敵人 / faux 假的(法文借字)',
    'thyme':      '⚠️ 同音字:thyme 百里香(th 不發音)/ time 時間',
    'reel':       '⚠️ 同音字:reel 短片/捲 / real 真實',
    'gene':       '⚠️ 同音字:gene 基因 / jean 牛仔布/人名',
    'atom':       '⚠️ 同音字:atom 原子 / Adam 亞當',
    'idol':       '⚠️ 同音字:idol 偶像 / idle 空閒的',
    'idle':       '⚠️ 同音字:idle 空閒的 / idol 偶像',
    'strait':     '⚠️ 同音字:strait 海峽 / straight 直的',
    'bald':       '⚠️ 同音字:bald 禿頭的 / bawled 大哭(過去式)',
    'bold':       '⚠️ 同音字:bold 勇敢的 / bowled 投保齡球(過去式)',
    'cast':       '⚠️ 同音字:cast 演員陣容 / caste 種姓',
    'caste':      '⚠️ 同音字:caste 種姓 / cast 演員陣容',
    'stocks':     '⚠️ 同音字:stocks 股票 / stalks 莖',
    'plates':     '⚠️ 同音字:plates 盤子/槓片 / plaits 辮子(英式)',
    'breach':     '⚠️ 同音字:breach 違反/外洩 / breech 槍尾/臀位',
    'discrete':   '⚠️ 同音字:discrete 分離的 / discreet 謹慎的',
    'discreet':   '⚠️ 同音字:discreet 謹慎的 / discrete 分離的',
    'moral':      '⚠️ 易混字:moral 道德的 / morale 士氣',
    'statute':    '⚠️ 易混字:statute 法令 / statue 雕像 / stature 身材',
    'statue':     '⚠️ 易混字:statue 雕像 / statute 法令 / stature 身材',
    'pane':       '⚠️ 同音字:pane 窗玻璃 / pain 疼痛',
    'mason':      '⚠️ 同音字:mason 泥水匠 / Mason 人名',
    'gulf':       '⚠️ 易混字:gulf 海灣 / golf 高爾夫(差一個字母)',
    'ally':       '⚠️ 近音字:ally 盟友 / alley 巷子',
    'alley':      '⚠️ 近音字:alley 巷子 / ally 盟友',
    'canvas':     '⚠️ 易混字:canvas 畫布 / canvass 拉票(差一個 s)',
    'canvass':    '⚠️ 易混字:canvass 拉票 / canvas 畫布(差一個 s)',
    'palette':    '⚠️ 易混字:palette 調色盤 / pallet 棧板 / palate 味覺(三胞胎)',
    'palate':     '⚠️ 易混字:palate 味覺 / palette 調色盤 / pallet 棧板',
    'councilor':  '⚠️ 同音字:councilor 議員 / counselor 諮商師',
    'consul':     '⚠️ 易混字:consul 領事 / council 議會 / counsel 建議',
    'council':    '⚠️ 已標(議會 vs counsel 建議)',  # 已在前面標過
    'flair':      '⚠️ 同音字:flair 天分 / flare 閃光',
    'flare':      '⚠️ 同音字:flare 閃光 / flair 天分',
    'hoarse':     '⚠️ 同音字:hoarse 沙啞的 / horse 馬',
    'haunt':      '⚠️ 近音字:haunt 糾纏 / hunt 狩獵',
    'haul':       '⚠️ 同音字:haul 拖拉 / hall 大廳',
    'heir':       '⚠️ 同音字:heir 繼承人(h 不發音)/ air 空氣',
    'yolk':       '⚠️ 同音字:yolk 蛋黃 / yoke 軛(l 不發音)',
    'yoke':       '⚠️ 同音字:yoke 軛 / yolk 蛋黃',
    'rite':       '⚠️ 同音字:rite 儀式 / right 對的 / write 寫',
    'feint':      '⚠️ 同音字:feint 佯攻 / faint 昏倒',
    'corps':      '⚠️ 同音字:corps 軍團(p、s 不發音)/ core 核心',
    'corpse':     '⚠️ 易混字:corpse 屍體 / corps 軍團(corps 的 p、s 不發音)',
    'dual':       '⚠️ 同音字:dual 雙重的 / duel 決鬥',
    'duel':       '⚠️ 同音字:duel 決鬥 / dual 雙重的',
    'wail':       '⚠️ 同音字:wail 慟哭 / whale 鯨魚',
    'whale':      '⚠️ 同音字:whale 鯨魚 / wail 慟哭',
    'wreath':     '⚠️ 同音字:wreath 花環 / writhe 扭動(wr 中 w 不發音)',

    # === 多義字(同字多義) ===
    'bank':       '⚠️ 一字多義:bank 銀行 / 河岸',
    'bat':        '⚠️ 一字多義:bat 蝙蝠 / 球棒 / 拳擊',
    'fall':       '⚠️ 一字多義:fall 跌倒 / 秋天 / 落下',
    'spring':     '⚠️ 一字多義:spring 春天 / 彈簧 / 泉水',
    'park':       '⚠️ 一字多義:park 公園 / 停車(動詞)',
    'order':      '⚠️ 一字多義:order 點餐 / 順序 / 命令',
    'mean':       '⚠️ 一字多義:mean 刻薄的 / 意思(動詞)/ 平均值',
    'kind':       '⚠️ 一字多義:kind 善良的 / 種類',
    'wind':       '⚠️ 兩種發音:wind ㄨㄧㄣㄉ=風 / ㄨㄞㄣㄉ=纏繞、上發條',
    'live':       '⚠️ 兩種發音:live ㄌㄧㄈ=居住(動詞)/ ㄌㄞㄈ=現場直播(形容詞)',
    'minute':     '⚠️ 兩種發音:minute ㄇㄧㄋㄧㄊ=分鐘 / ㄇㄞㄋㄩㄊ=微小',
    'close':      '⚠️ 兩種發音:close ㄎㄌㄛㄗ=關閉(動詞)/ ㄎㄌㄛㄙ=近(形容詞)',
    'can':        '⚠️ 一字多義:can 可以(助動詞)/ 罐頭',
    'like':       '⚠️ 一字多義:like 喜歡 / 像、如同',
    'pop':        '⚠️ 一字多義:pop 流行(音樂)/ 爆開 / 汽水',
    'tie':        '⚠️ 一字多義:tie 領帶 / 平手 / 綁起來',
    'fan':        '⚠️ 一字多義:fan 電風扇 / 粉絲(迷)',
    'chest':      '⚠️ 一字多義:chest 胸口 / 箱子(寶箱)',
    'cap':        '⚠️ 一字多義:cap 鴨舌帽 / 上限',
    'palm':       '⚠️ 一字多義:palm 手掌 / 棕櫚樹',
    'rock':       '⚠️ 一字多義:rock 石頭 / 搖滾(音樂)',
    'wave':       '⚠️ 一字多義:wave 波浪 / 揮手',
    'country':    '⚠️ 一字多義:country 國家 / 鄉村',
    'trip':       '⚠️ 一字多義:trip 旅行 / 絆倒',
    'band':       '⚠️ 一字多義:band 樂團 / 帶子、橡皮筋',
    'fly':        '⚠️ 一字多義:fly 飛 / 蒼蠅',
    'rose':       '⚠️ 一字多義:rose 玫瑰花 / 玫瑰色 / rise 過去式(升起了)',
    'fine':       '⚠️ 一字多義:fine 還好 / 罰款',
    'miss':       '⚠️ 一字多義:miss 想念 / 錯過',
    'pine':       '⚠️ 一字多義:pine 松樹 / 思念(pine for)',
    'foot':       '⚠️ 一字多義:foot 腳 / 英尺(長度單位);複數 feet 不規則',
    'head':       '⚠️ 一字多義:head 頭 / 帶頭(動詞)/ 朝向',
    'face':       '⚠️ 一字多義:face 臉 / 面對(動詞)',
    'hand':       '⚠️ 一字多義:hand 手 / 遞給(動詞)',
    'lead':       '⚠️ 一字多義同形異音:lead /liːd/ 帶領 / lead /lɛd/ 鉛',
    'mass':       '⚠️ 一字多義:mass 質量/大量 / Mass 彌撒(看脈絡)',
    'box':        '⚠️ 一字多義:box 箱子 / 拳擊(動詞,boxing 字根)',
    'pad':        '⚠️ 一字多義:pad 墊子 / 衛生棉',

    # === 易混字(拼字像但意義不同)===
    'desert':     '⚠️ 易混字:desert 沙漠 / dessert 甜點(雙 s)/ desert 動詞(拋棄)',
    'principal':  '⚠️ 已標(校長 vs principle 原則)',
    'effect':     '⚠️ 已標(結果 vs affect 影響)',
    'except':     '⚠️ 已標(除…之外 vs accept 接受)',
    'adapt':      '⚠️ 易混字:adapt 適應 / adopt 收養/採用(差一個字母)',
    'adopt':      '⚠️ 易混字:adopt 收養/採用 / adapt 適應(差一個字母)',
    'ensure':     '⚠️ 易混字:ensure 確保 / assure 向…保證 / insure 投保',
    'assure':     '⚠️ 易混字:assure 向…保證 / ensure 確保 / insure 投保',
    'conscious':  '⚠️ 易混字:conscious 有意識的 / conscience 良心',
    'libel':      '⚠️ 易混字:libel 誹謗罪 / liable 該負責的 / label 標籤',
    'liable':     '⚠️ 易混字:liable 該負責的 / libel 誹謗罪 / label 標籤',

    # === 不規則過去式撞同音 ===
    'led':        '⚠️ 同音字:led(lead 過去式)/ lead 鉛(金屬,/lɛd/)',
    'flew':       '⚠️ 同音字:flew(fly 過去式)/ flu 流感',
    'flu':        '⚠️ 同音字:flu 流感 / flew(fly 過去式)',
    'sent':       '⚠️ 同音字:sent 寄(過去式)/ cent 分(錢)/ scent 香味',
    'cent':       '⚠️ 同音字:cent 分(錢)/ sent 寄(過去式)/ scent 香味',
    'scent':      '⚠️ 同音字:scent 香味 / sent 寄(過去式)/ cent 分(錢)',
    'meet':       '⚠️ 同音字:meet 遇見 / meat 肉',
    'left':       '⚠️ 一字多義:left 左邊 / leave 過去式(離開了)',
    'saw':        '⚠️ 一字多義:saw see 過去式(看見了)/ 鋸子',
    'dove':       '⚠️ 一字多義:dove 鴿子 / dive 過去式(跳水了)',

    # === 連音/兩字寫成一字易混 ===
    'maybe':      '⚠️ 易混:maybe(也許,副詞)/ may be(可能是,動詞片語)— 分開寫意思不同',
    'sealevel':   '⚠️ sea 同音 see(看)',
    'rockinghorse':'⚠️ horse(馬)同音 hoarse(沙啞的)',
    'soulmate':   '⚠️ soul(靈魂)同音 sole(唯一的/鞋底)',
    'bearmarket': '⚠️ bear(熊)同音 bare(赤裸的)',
    'stakeholder':'⚠️ stake(利害關係)同音 steak(牛排)',
    'stationarybike':'⚠️ stationary(靜止的)易混 stationery(文具)— 只差 a/e',
    'sweet16':    '⚠️ sweet 同音 suite(套房/組曲)',
    'weights':    '⚠️ weight(重量)同音 wait(等待)',
}

# 套用(若已有 homophone-note 就跳過)
n_add = 0
n_skip = 0
for word, note in HOMO.items():
    if word not in idx:
        n_skip += 1
        continue
    if 'homophone-note' in idx[word]:
        n_skip += 1
        continue
    idx[word]['homophone-note'] = note
    n_add += 1

with open(VOCAB,'w',encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"新增易混提示: {n_add}")
print(f"略過(已標/不存在): {n_skip}")
print(f"總 homophone: {sum(1 for w in words if 'homophone-note' in w)}")
